# Generated by Django 3.2.9 on 2021-11-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Html_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Css_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_content', models.TextField()),
                ('html_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnCSS.html_content')),
            ],
        ),
    ]
